import OurApp from '../components/OurApp';
import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/NavBar';
import HeroSection from '../components/HeroSection';
import AboutUs from '../components/AboutUs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Play Genius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar text="text-white" />
      <HeroSection />
      <OurApp />
      <AboutUs />
      <Footer />
    </>
  );
}
